RedTurtle/design-volto-theme

.eslintrc, jsconfig.json, mrs.developer.json, package.json, src/config.js, src/customizations/components/theme/Footer/Footer.jsx, src/reducers/index.js, yarn.lock
=> added cookieconsent addon

package.json, src/components/DesignTheme/View/Commons/Actions.jsx, src/components/DesignTheme/View/Commons/Attachment.jsx, src/components/DesignTheme/View/Commons/Attachments.jsx, src/components/DesignTheme/View/Commons/CuredBy.jsx, src/components/DesignTheme/View/Commons/Gallery.jsx, src/components/DesignTheme/View/Commons/GenericCard.jsx, src/components/DesignTheme/View/Commons/Locations.jsx, src/components/DesignTheme/View/Commons/Metadata.jsx, src/components/DesignTheme/View/Commons/NewsCard.jsx, src/components/DesignTheme/View/Commons/OfficeCard.jsx, src/components/DesignTheme/View/Commons/PageHeader.jsx, src/components/DesignTheme/View/Commons/RelatedNews.jsx, src/components/DesignTheme/View/Commons/RichTextArticle.jsx, src/components/DesignTheme/View/Commons/Sharing.jsx, src/components/DesignTheme/View/Commons/Venue.jsx, src/components/DesignTheme/View/Commons/WideImage.jsx, src/components/DesignTheme/View/Commons/index.jsx, src/components/DesignTheme/View/NewsItemView.jsx, src/components/DesignTheme/View/PersonaView.jsx, src/components/DesignTheme/View/UOView.jsx, src/components/DesignTheme/View/ViewUtils.jsx, src/components/DesignTheme/View/__tests__/PersonaView.test.jsx, src/components/DesignTheme/index.js, src/config.js, theme/DesignTheme/Views/_common.scss
Ho aggiunto la vista persona. 
Faccio una PR per iniziare la revisione, ma ci sono diverse cose che necessito di guardare insieme.
I test ad un certo punto mi si sono "bloccati". Hanno iniziato a fallire e non capisco perché gli elementi che cerco non siano in pagina.
=> add Persona View

src/components/DesignTheme/View/PaginaArgomentoView.jsx, src/components/DesignTheme/View/PersonaView.jsx, src/components/DesignTheme/View/ServizioView.jsx, src/components/DesignTheme/View/__tests__/PaginaArgomento.test.jsx, src/components/DesignTheme/index.js, src/config.js
@pnicolli sa di cosa si parla.
@deodorhunter un po'
@damiDevRT per nulla. vedete voi chi da un occhio anche se ormai son tutte uguali ste viste.
Questa è la parte no behaviour blocchi.
La storia dei blocchi con il behaviour credo l'abbia già vista martina, ma settimana prossima intanto che faccio la storia dei blocchi di testata, controllo
=> [new] aggiunto vista pagina argomento

src/components/DesignTheme/Blocks/ArgomentoTitle/Edit.jsx, src/components/DesignTheme/Blocks/ArgomentoTitle/View.jsx, src/components/DesignTheme/View/PaginaArgomentoView.jsx, src/components/DesignTheme/View/PaginaArgomentoViewNoBlocks.jsx, src/components/DesignTheme/View/PersonaView.jsx, src/components/DesignTheme/View/ServizioView.jsx, src/components/DesignTheme/View/__tests__/PaginaArgomento.test.jsx, src/components/DesignTheme/index.js, src/components/DesignTheme/manage/Widgets/TextEditorWidget.jsx, src/config.js, src/customizations/components/theme/App/App.jsx, theme/DesignTheme/Blocks/_titolo_argomento.scss, theme/site.scss
Vista della pagina argomento con i blocchi abilitati e blocco titolo / a portata di click
=> Pagina argomento view us 9411

src/customizations/components/manage/Edit/Edit.jsx
Override della vista di Edit da [](https://github.com/plone/volto/issues/1594)
Da considerarsi una patch, attendere il core per i test
=> [fix] overrided Edit.jsx view

src/config.js
Reintrodotto l'import di news.svg rimosso per errore
=> fix newsSVG

src/components/DesignTheme/View/PersonaView.jsx
https://redturtle.tpondemand.com/RestUI/Board.aspx#page=board/5034431133910786991&appConfig=eyJhY2lkIjoiNjMxQzMxODg1OTYwRDhGODAxMDM1QjMyNkUwMzE3NDIifQ==&boardPopup=userstory/11203/silent
=> aggiunto href al link telefonico

src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateCompact.jsx, src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateDefault.jsx, src/components/ItaliaTheme/Search/utils.js, src/components/ItaliaTheme/View/Commons/PageHeaderNav.jsx, src/components/ItaliaTheme/View/Commons/SearchSectionForm.jsx, src/components/ItaliaTheme/View/PageView.jsx, src/components/ItaliaTheme/View/PaginaArgomentoView.jsx, src/components/ItaliaTheme/View/index.js, src/components/ItaliaTheme/index.js, src/config.js, src/customizations/components/theme/Search/Search.jsx, theme/ItaliaTheme/Components/_pageHeader.scss, theme/site.scss, yarn.lock
Testata nelle pagine. 
Prendere giu il branch us_9426 di design.plone.contenttypes.
Titolo e descrizione si editano dalla sidebar.
Sempre dalla sidebar è possibile inserire il testo che verrà mostrato sulla colonna di destra.
Se si spunta la casella 'mostra ricerca' verrà visualizzata la form di ricerca che permettere di ricercare da quel path li in giu.
Se si spunta la casella 'mostra navigazione' verrà visualizzata la navigazione sulla colonna di destra (espandibile nel caso ci siano più di 6 elementi).
=> Page header

src/components/ItaliaTheme/Blocks/Listing/Options/RibbonCardTemplateOptions.jsx, src/components/ItaliaTheme/Blocks/Listing/Options/SimpleCardListingOptions.jsx, src/components/ItaliaTheme/Blocks/Listing/RibbonCardTemplate.jsx, src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateCompact.jsx, src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateDefault.jsx, src/config.js, src/customizations/components/manage/Blocks/Listing/ListingStyle.jsx, theme/ItaliaTheme/Blocks/_listing.scss, theme/extras/_blocks.scss, theme/site.scss
- si può scegliere il titlolo
- Si può scegliere se mostrare il nastro solo sul primo elemento o su tutti (default)
- si può scegliere se mostrare il link al dettaglio di ogni elemento (verrà mostrato nel footer della card) ed eventualmente anche il testo da mostrare.
- si può decidere se mostrare lo sfondo grigio
=> Ribbon card template

src/components/ItaliaTheme/View/Commons/Dates.jsx, src/components/ItaliaTheme/View/Commons/PageHeader.jsx, src/components/ItaliaTheme/View/Commons/Sponsors.jsx, src/components/ItaliaTheme/View/EventoView.jsx
mostrata la ricorrenza nella view dell evento. 
Se sono presenti date aggiuntive/date escluse queste verranno mostrate nella sezione Date e orari
=> Event recurrence

src/components/ItaliaTheme/View/Commons/RelatedArticles.jsx, src/components/ItaliaTheme/View/Commons/RelatedNews.jsx, src/components/ItaliaTheme/View/Commons/RichTextArticles.jsx, src/components/ItaliaTheme/View/VenueView.jsx
us [https://redturtle.tpondemand.com/restui/board.aspx?#page=board/5034431133910786991&appConfig=eyJhY2lkIjoiNjMxQzMxODg1OTYwRDhGODAxMDM1QjMyNkUwMzE3NDIifQ==&boardPopup=userstory/12037/silent](https://redturtle.tpondemand.com/restui/board.aspx?#page=board/5034431133910786991&appConfig=eyJhY2lkIjoiNjMxQzMxODg1OTYwRDhGODAxMDM1QjMyNkUwMzE3NDIifQ==&boardPopup=userstory/12037/silent)
=> aggiunta campo sede di

src/components/ItaliaTheme/View/Commons/Dates.jsx, src/components/ItaliaTheme/View/Commons/OfficeCard.jsx, src/components/ItaliaTheme/View/Commons/RichTextArticle.jsx, src/components/ItaliaTheme/View/EventoView.jsx, src/components/ItaliaTheme/View/VenueView.jsx
fix vari sopratutto grafici su evento e luogo view
=> Fix events

src/customizations/components/theme/Navigation/Navigation.jsx
Come #122 ma per tutto il menu di navigazione (ha effetto su mobile)
=> dev: close mobile menu when navigating clicking on links

src/components/ItaliaTheme/View/Commons/EventLocation.jsx
=> dev: added city to event location address

src/components/ItaliaTheme/View/Commons/Attachments.jsx, src/components/ItaliaTheme/View/Commons/Gallery.jsx, src/components/ItaliaTheme/View/EventoView.jsx, src/components/ItaliaTheme/View/NewsItemView.jsx, src/components/ItaliaTheme/View/PersonaView.jsx, src/components/ItaliaTheme/View/ServizioView.jsx, src/components/ItaliaTheme/View/UOView.jsx, src/components/ItaliaTheme/View/VenueView.jsx, src/helpers/contentHelper.js, src/helpers/index.js
> la sezione viene caricata dopo il caricamento dell'oggetto, pertanto all'inizio, quando viene costruito il menu laterale, quella sezione non esiste e non viene messa nel menu laterale.
=> us 12897 - allegati: handled items_total in attachments

src/components/ItaliaTheme/Blocks/Alert/Edit.jsx, src/components/ItaliaTheme/Blocks/Alert/View.jsx, src/components/ItaliaTheme/Blocks/ArgomentoTitle/View.jsx, src/components/ItaliaTheme/Blocks/ArgumentsInEvidence/Block.jsx, src/components/ItaliaTheme/View/Commons/TextOrBlocks.jsx, src/components/ItaliaTheme/View/PageView/PageView.jsx, src/components/ItaliaTheme/View/PaginaArgomentoView/PaginaArgomentoView.jsx, src/components/ItaliaTheme/manage/Widgets/TextEditorWidget.jsx, src/customizations/components/theme/Search/Search.jsx, src/reducers/index.js
Le import del config vanno fatte con~/config e non con @italia/config, perchè altrimenti non si riesce a leggere la configurazione del sito figlio
=> fixed imports of config

src/components/ItaliaTheme/Blocks/ArgumentsInEvidence/BodyWrapper.jsx, src/components/ItaliaTheme/Blocks/Listing/CompleteBlockLinksTemplate.jsx, src/components/ItaliaTheme/Blocks/SearchSections/Body.jsx, src/components/ItaliaTheme/Header/HeaderCenter.jsx, theme/ItaliaTheme/Blocks/_argumentsInEvidence.scss, theme/ItaliaTheme/Blocks/_completeBlockLinkstemplate.scss, theme/ItaliaTheme/Blocks/_searchSections.scss, theme/ItaliaTheme/_main.scss, theme/_site-variables.scss
Piccoli grandi fix sulle variabili dei colori
=> Fix colors

src/components/ItaliaTheme/Footer/FooterMain.jsx, src/components/ItaliaTheme/Header/HeaderCenter.jsx, src/components/ItaliaTheme/Logo/Logo.jsx, src/components/ItaliaTheme/LogoFooter/LogoFooter.jsx, src/components/ItaliaTheme/index.js
Questo rende le customizzazioni molto più semplici
=> dev: moved logo to a separated component

src/components/ItaliaTheme/Blocks/ArgumentsInEvidence/Background.jsx, src/components/ItaliaTheme/Blocks/ArgumentsInEvidence/View.jsx, src/components/ItaliaTheme/Blocks/SearchSections/Background.jsx, src/components/ItaliaTheme/Blocks/SearchSections/Body.jsx, src/components/ItaliaTheme/index.js, theme/ItaliaTheme/Blocks/_argumentsInEvidence.scss, theme/ItaliaTheme/Blocks/_searchSections.scss
- aggiunto componente customizzabile per background argumentsInEvidence
- aggiunto componente customizzabile per background searchSections
- fixes searchSections h2 vs container
=> Arguments in evidence + search sections background

src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx, src/components/ItaliaTheme/View/Commons/BandoDates.jsx, theme/ItaliaTheme/Blocks/_bandiInEvidenceTemplate.scss
Fix veramente triviale che porta il tempo in utc e poi in local time.
=> fix view local time nella vista bando

src/components/ItaliaTheme/Blocks/Calendar/Body.jsx, src/components/ItaliaTheme/Blocks/Calendar/Item.jsx, theme/ItaliaTheme/Blocks/_calendar.scss
Questa pr risolve dei problemi di visualizzazione in edit del calendario, non venivano paginati correttamente i giorni e non si aggiornava automaticamente al cambio di filtro
=> fix calendar in edit mode

src/components/ItaliaTheme/Blocks/EventSearch/Body.jsx, src/components/ItaliaTheme/Blocks/EventSearch/Edit.jsx, src/components/ItaliaTheme/Blocks/EventSearch/FilterBlocks/DateFilter.jsx, src/components/ItaliaTheme/Blocks/EventSearch/FilterBlocks/SelectFilter.jsx, src/components/ItaliaTheme/Blocks/EventSearch/FilterBlocks/TextFilter.jsx, src/components/ItaliaTheme/Blocks/EventSearch/FilterBlocks/index.js, src/components/ItaliaTheme/Blocks/EventSearch/Item.jsx, src/components/ItaliaTheme/Blocks/EventSearch/ListingSidebar.jsx, src/components/ItaliaTheme/Blocks/EventSearch/View.jsx, src/components/ItaliaTheme/Blocks/Listing/CardWithImageTemplate.jsx, src/components/ItaliaTheme/Header/ParentSiteMenu.jsx, src/config.js, src/customizations/components/manage/Widgets/SelectWidget.jsx, theme/ItaliaTheme/Blocks/_eventSearch.scss, theme/site.scss
Componente per la ricerca di eventi.
Per aggiungere nuovi filtri purtroppo non ho avuto il tempo di renderlo configurabile al di fuori del componente stesso, quindi quando lo si vuole fare, bisogna aggiungerlo su design volto theme oppure fare una customizzazione del componente "Body" e "ListingSidebar".
Se il componente viene messo in un sottosito, cerca i soli eventi del sottosito, stessa cosa per il filtro dei luoghi.
Attualmente per fare listare gli eventi, usa il template "CardWithImageTemplate".
=> Componente ricerca eventi

razzle.config.js, src/components/ItaliaTheme/View/BandoView/BandoView.jsx, src/components/ItaliaTheme/View/Commons/Attachments.jsx, src/components/ItaliaTheme/View/Commons/CuredBy.jsx, src/components/ItaliaTheme/View/Commons/SmallVenue.jsx, src/components/ItaliaTheme/View/Commons/VenuesSmall.jsx, src/components/ItaliaTheme/View/DocumentoView/DocumentoView.jsx, src/components/ItaliaTheme/View/DocumentoView/Module.jsx, src/components/ItaliaTheme/View/DocumentoView/Modules.jsx, src/components/ItaliaTheme/View/NewsItemView/NewsItemView.jsx, src/components/ItaliaTheme/View/ServizioView/ServizioView.jsx, src/components/ItaliaTheme/View/VenueView/VenueView.jsx, src/helpers/contentHelper.js, theme/ItaliaTheme/Views/_common.scss, theme/ItaliaTheme/Views/_evento.scss, theme/ItaliaTheme/Views/_slider.scss, theme/ItaliaTheme/Views/_sponsors.scss, theme/ItaliaTheme/Views/_uo.scss, theme/bootstrap-override/bootstrap-italia/_card.scss, theme/site.scss, yarn.lock
sistemate le view dei content type per fare in modo che funizioni bene anche senza la fullObjects.
Fatto qualche fix e refactor
=> Volto10 and depth

src/components/ItaliaTheme/View/PageView/PageView.jsx, theme/ItaliaTheme/Components/_pageHeader.scss
=> added immagine_testata_field view

src/components/ItaliaTheme/Blocks/ArgumentsInEvidence/BottomBody.jsx, src/components/ItaliaTheme/Blocks/Calendar/Item.jsx, src/components/ItaliaTheme/Blocks/Listing/AmministrazioneTrasparenteTablesTemplate.jsx, src/components/ItaliaTheme/Blocks/Listing/CardWithImageTemplate.jsx, src/components/ItaliaTheme/Blocks/Listing/GridGalleryTemplate.jsx, src/components/ItaliaTheme/Blocks/Listing/InEvidenceTemplate.jsx, src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateDefault.jsx, src/components/ItaliaTheme/Blocks/Listing/serviziAmministrazioneTrasparenteTemplate.jsx, src/components/ItaliaTheme/Blocks/NewsHome/Body.jsx, src/components/ItaliaTheme/Header/HeaderCenter.jsx, src/components/ItaliaTheme/View/CartellaModulisticaView/DocRow.jsx, src/components/ItaliaTheme/View/Commons/Events.jsx, src/components/ItaliaTheme/View/Commons/GenericCard.jsx, src/components/ItaliaTheme/View/Commons/NewsCard.jsx, src/components/ItaliaTheme/View/Commons/OfficeCard.jsx, src/components/ItaliaTheme/View/Commons/SmallVenue.jsx, src/components/ItaliaTheme/View/EventoView/EventoView.jsx, src/components/ItaliaTheme/View/PaginaArgomentoView/PaginaArgomentoView.jsx, src/components/ItaliaTheme/View/TrasparenzaView/DettagliProcedimentiView.jsx, src/customizations/components/theme/Search/Search.jsx
Usato UniversalLink che gestisce link interni, esterni, download
=> Universal link

src/components/ItaliaTheme/Blocks/Listing/PhotogalleryTemplate.jsx, src/customizations/components/manage/Blocks/Listing/ImageGallery.jsx, theme/ItaliaTheme/Blocks/_photogallerytemplate.scss
Aggiunta descrizione nei template gallery per i listing.
Se non c'è la descrizione, guarda il campo Diritti.
=> feat: add caption in image gallery templates

src/components/ItaliaTheme/Blocks/Listing/AmministrazioneTrasparenteTablesTemplate.jsx, src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx, src/components/ItaliaTheme/Blocks/Listing/CompleteBlockLinksTemplate.jsx, src/components/ItaliaTheme/Blocks/Listing/GridGalleryTemplate.jsx, src/components/ItaliaTheme/Blocks/Listing/RibbonCardTemplate.jsx, src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateCompact.jsx, src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateDefault.jsx, theme/ItaliaTheme/Blocks/_completeBlockLinkstemplate.scss, theme/ItaliaTheme/Subsites/ItaliaTheme/_common.scss, theme/ItaliaTheme/_common.scss
=> fixed listing linkmore button

theme/ItaliaTheme/Print/_all_pages.scss, theme/ItaliaTheme/Print/_bandi.scss, theme/ItaliaTheme/Print/_event.scss, theme/ItaliaTheme/Print/_news_items.scss, theme/ItaliaTheme/Print/_page.scss, theme/ItaliaTheme/Print/_persona.scss, theme/ItaliaTheme/Print/_servizio.scss, theme/ItaliaTheme/Views/_evento.scss, theme/site.scss
=> Stili stampa

theme/ItaliaTheme/Print/_all_pages.scss
Fix che risolve il problema che su firefox viene stampata solo la prima pagina
=> fix print firefox

Dockerfile
Non cambia nulla a livello di "cosa fa", è solo più lineare nella gestione dei permessi dei file e ha meno step da eseguire.
=> Migliorato dockerfile in leggibilità e performance

theme/_cms-ui.scss
Aumentata la larghezza del suo container e aggistati allinaementi delle label
=> style: login form width

src/components/ItaliaTheme/LanguageSelector/LanguageSelector.jsx, src/config/italiaConfig.js, src/customizations/volto/components/theme/Header/Header.jsx
quando si cambiava la lingua dal selettore della lingua, alcune traduzioni nella testata non venivano modificate
=> fix: fixed loading locales on language change

src/components/ItaliaTheme/View/CartellaModulisticaView/CartellaModulisticaView.jsx, src/components/ItaliaTheme/View/Commons/PageHeader/PageHeader.jsx, src/components/ItaliaTheme/View/PageView/PageView.jsx
- Added leadimage in CartellaModulistica
- Added Tassonomia argomenti in page header (for content type Document)
=> chore: added leadimage in cartellaModulisitica

src/config/italiaConfig.js
Remove `amministrazioneTrasparenteTablesTemplate` listing template
=> refactor: remove listing amministrazioneTrasparenteTablesTemplate

package.json, yarn.lock
=> chore: update volto with fix_sidebar_popup_clickoutside

locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/volto.pot, src/components/ItaliaTheme/Breadcrumbs/Breadcrumbs.jsx, src/components/ItaliaTheme/View/PaginaArgomentoView/PaginaArgomentoView.jsx, src/components/ItaliaTheme/index.js, src/customizations/volto/components/theme/Breadcrumbs/Breadcrumbs.jsx
to avoid color contrast problems on light images:
=> chore: moved breadcrumbs in TitleWrapper for Pagina Argomento

locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/volto.pot, src/components/ItaliaTheme/Blocks/Listing/SliderTemplate.jsx, src/config/Blocks/ListingOptions/index.js, src/config/Blocks/ListingOptions/sliderTemplate.js, src/config/Blocks/listingVariations.js, theme/ItaliaTheme/Blocks/_sliderTemplate.scss
Added slidesToShow property to the Slider template
=> chore: added slidesToShow prop to sliderTemplate Listing

locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/volto.pot, src/components/ItaliaTheme/GalleryPreview/GalleryPreview.jsx, src/components/ItaliaTheme/View/Commons/Gallery.jsx, src/components/ItaliaTheme/index.js, theme/ItaliaTheme/Components/_galleryPreview.scss, theme/ItaliaTheme/Views/_slider.scss, theme/site.scss
Nel componente che disegna la gallery di una cartella di immagini nella vista di un content-type, è stato aggiunto, al click sull'immagine la preview dell'immagine in una modale.
=> Gallery preview

locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/volto.pot, src/components/ItaliaTheme/Blocks/HighlightedContent/Body.jsx, src/components/ItaliaTheme/Blocks/Listing/CardWithImageTemplate.jsx, src/components/ItaliaTheme/Blocks/Listing/CardWithSlideUpTextTemplate.jsx, src/components/ItaliaTheme/Blocks/Listing/Commons/utils.js, src/components/ItaliaTheme/Blocks/Listing/InEvidenceTemplate.jsx, src/components/ItaliaTheme/Blocks/Listing/RibbonCardTemplate.jsx, src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateDefault.jsx
Variazione delle props per una modifica richiesta su GDF
=> Added listing custom props

locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/volto.pot, src/components/ItaliaTheme/Blocks/Calendar/Body.jsx, src/components/ItaliaTheme/Blocks/Calendar/ListingSidebar.jsx, src/components/ItaliaTheme/index.js, src/components/ItaliaTheme/manage/Widgets/LocationFiltersWidget.jsx, src/config/Widgets/widgets.js, theme/ItaliaTheme/Blocks/_calendar.scss
feat: add calendar block slider arrows
fix: calendar block columns box-shadow was missing
feat: add additional location filters to calendar block
=> Improve calendar block

locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/volto.pot, src/components/ItaliaTheme/Blocks/Listing/PhotogalleryTemplate.jsx, src/components/ItaliaTheme/GalleryPreview/GalleryPreview.jsx, theme/ItaliaTheme/Blocks/_photogallerytemplate.scss
Standardizzato le dimensioni delle immagini per il blocco elenco Photogallery
=> fix: fixed standard size for photogallery images

jsconfig.json, locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/volto.pot, mrs.developer.json, package.json, src/components/ItaliaTheme/Blocks/VideoGallery/Block/EditBlock.jsx, src/components/ItaliaTheme/Blocks/VideoGallery/Block/ViewBlock.jsx, src/components/ItaliaTheme/View/Commons/EmbeddedVideo.jsx, src/components/ItaliaTheme/View/Commons/Gallery.jsx, src/config/italiaConfig.js, src/config/volto-gdpr-privacy-defaultPanelConfig.js, src/customizations/volto-gdpr-privacy/components/CookieBanner/ui/Button.jsx, src/customizations/volto-gdpr-privacy/components/CookieBanner/ui/Container.jsx, src/customizations/volto/components/manage/Blocks/Video/View.jsx, src/customizations/volto/components/theme/Footer/Footer.jsx, theme/ItaliaTheme/Addons/volto-gdpr-privacy.scss, theme/site.scss, yarn.lock
New gdpr privacy manager with addo volto-gdpr-privacy
=> Gdpr privacy

locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/volto.pot, src/components/ItaliaTheme/Blocks/HeroImageLeft/HeroSidebar.jsx, src/components/ItaliaTheme/Blocks/HeroImageLeft/StoresButtons.jsx, src/components/ItaliaTheme/Blocks/TextCard/CardWithImage/Block.jsx, src/components/ItaliaTheme/Blocks/TextCard/CardWithImage/Edit.jsx, src/components/ItaliaTheme/Blocks/TextCard/CardWithImage/Sidebar.jsx, theme/ItaliaTheme/Blocks/_cardWithImageTextBlock.scss, theme/ItaliaTheme/Blocks/_hero.scss, theme/site.scss
- Aggiornato blocco Hero con la possibilità di aggiungere un link esterno o interno, più bugfix del layout mobile.
- Aggiunte nuove funzionalità al blocco Testo con Immagine, tra cui la possibilità di allineare l'immagine a destra, decidere quanto spazio occupa e l'alterazione o meno di essa, più codereview del componente.
=> Update card with image block

locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/volto.pot, src/components/ItaliaTheme/View/UOView/UOContacts.jsx, src/components/ItaliaTheme/View/UOView/UODocuments.jsx, src/components/ItaliaTheme/View/UOView/UOPeople.jsx, src/components/ItaliaTheme/View/UOView/UOServices.jsx, src/components/ItaliaTheme/View/UOView/UOStructure.jsx, src/components/ItaliaTheme/View/UOView/UOView.jsx, src/components/ItaliaTheme/View/UOView/UOWhatDoesItDo.jsx, src/components/ItaliaTheme/View/index.js
Splittata la vista della UO per consentire una più facile customizzazione delle varie parti e, permettere eventualmente un riordinamento facile delle sezione in una customizzazione
=> feat: splitted UOView in separated sections components

locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/volto.pot, src/components/ItaliaTheme/Blocks/EventSearch/Body.jsx, src/components/ItaliaTheme/Blocks/EventSearch/Sidebar.jsx
Aggiunta l'opzione 'Di default, mostra i risultati' al blocco di ricerca eventi.
=> feat: added show_default_results in EventsSearch block

locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/volto.pot, src/components/ItaliaTheme/View/VenueView/VenueAccessMode.jsx, src/components/ItaliaTheme/View/VenueView/VenueContacts.jsx, src/components/ItaliaTheme/View/VenueView/VenueDescription.jsx, src/components/ItaliaTheme/View/VenueView/VenueMoreInfos.jsx, src/components/ItaliaTheme/View/VenueView/VenuePublicTimetable.jsx, src/components/ItaliaTheme/View/VenueView/VenueServices.jsx, src/components/ItaliaTheme/View/VenueView/VenueView.jsx, src/components/ItaliaTheme/View/VenueView/VenueWhere.jsx, src/components/ItaliaTheme/View/index.js
piano piano sto spezzettando tutte le view, in modo da non doverla customizzare tutta se serve customizzarne solo una parte
=> chore: splitted Venue view in multiple components

src/components/ItaliaTheme/Blocks/Listing/SliderTemplate.jsx, theme/ItaliaTheme/Blocks/_sliderTemplate.scss
Aggiunto un background neutro nel template elenco Slider che non mostrava la slide se non trovava l'immagine in testata.
=> fix: added placeholder background in slider template

package.json, yarn.lock
Updated mrs.developer to handle 'main' branch in addons
=> Fix mrs developer

src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx
Aggiunta nota per aggiornamenti di un bando Attivo o In corso nel template elenco Bandi
=> chore: added update note in bando listing template

mrs.developer.json, package.json, src/customizations/volto-form-block/components/FormView.jsx, yarn.lock
Aggiunto il flag 'invia una copia anche a questo indirizzo' per i campi di tipo email nelle form
e fissato un bug nei dati della form inviati a plone
=> Form sendtoemail and fixes

theme/ItaliaTheme/Blocks/_tableOfContents.scss
Modificato il blocco Indice dei contenuti in questo modo per una maggiore leggibilità
=> Table of content layout

package.json, yarn.lock
Added 'safe' attribute to cookies if site is in https
=> Safe cookie

mrs.developer.json, package.json, src/customizations/volto-form-block/components/Field.jsx, yarn.lock
Now, sent dates are in locale's format. 
Also fixed warning for text input to change from uncontrolled to be controlled
=> fix: form uncontrolled field and formatted date sent

package.json
Tutte le dipendenze sono compatibili
=> Aggiunta compatibilità con node 16

src/components/ItaliaTheme/View/Commons/LocationItem.jsx
Ho aggiunto il link nella card di un eventuale oggetto Luogo collegato alla UO come Sede principale
=> chore: added link to location contact

locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/volto.pot, src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx, src/components/ItaliaTheme/View/Commons/BandoDates.jsx, src/components/ItaliaTheme/View/Commons/PageHeader/PageHeaderBando.jsx, theme/ItaliaTheme/Blocks/_bandiInEvidenceTemplate.scss, theme/ItaliaTheme/Views/_bando.scss
Come colore del bando programmato ho scelto questo:
Sistemato anche un bug sull'accessibilità nel link del blocco listing Bando:
ora è così:
=> chore: added scheduled bando

locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/volto.pot, src/components/ItaliaTheme/Blocks/SearchSections/Background.jsx, src/components/ItaliaTheme/Blocks/SearchSections/BackgroundUser.jsx, src/components/ItaliaTheme/Blocks/SearchSections/Body.jsx, src/components/ItaliaTheme/Blocks/SearchSections/SideBar.jsx, src/components/ItaliaTheme/index.js, theme/ItaliaTheme/Blocks/_searchSections.scss
Block searchSections with possibility to add an existing image to background.
=> Search section background

src/components/ItaliaTheme/Blocks/Listing/PhotogalleryTemplate.jsx, src/components/ItaliaTheme/Blocks/Listing/SliderTemplate.jsx, theme/ItaliaTheme/Blocks/_photogallerytemplate.scss
- sistemato un bug sul pulsante play/pausa, se era attivo l'autoplay non compariva l'icona "pause"
- sistemato l'autoplay nel blocco photogallery che si bloccava dopo il primo scorrimento
- allineato verticalmente le immagini del blocco photogallery
=> fix: fixed autoplay and play button of photogallery and slider listing templates

src/components/ItaliaTheme/View/Commons/LocationItem.jsx, src/components/ItaliaTheme/View/Commons/Locations.jsx, src/components/ItaliaTheme/View/ServizioView/ServizioComeAccedere.jsx
=> feat: added map Where to contact section of Service CT

locales/de/LC_MESSAGES/volto.po, locales/en/LC_MESSAGES/volto.po, locales/fr/LC_MESSAGES/volto.po, locales/it/LC_MESSAGES/volto.po, locales/ja/LC_MESSAGES/volto.po, locales/nl/LC_MESSAGES/volto.po, locales/volto.pot, src/components/ItaliaTheme/View/Commons/LocationsMap.jsx, theme/ItaliaTheme/Components/_locationsMap.scss, theme/site.scss
Aggiunto popup al click sul pin di una mappa, contiene i link esterni a Google Maps, Apple Maps e Bing Maps.
=> feat: added popup on map pin

src/components/ItaliaTheme/Blocks/ArgumentsInEvidence/Body.jsx, src/components/ItaliaTheme/Blocks/ArgumentsInEvidence/Edit.jsx, src/components/ItaliaTheme/Blocks/ArgumentsInEvidence/View.jsx, src/components/ItaliaTheme/Blocks/CTABlock/Edit.jsx, src/components/ItaliaTheme/Blocks/CTABlock/View.jsx
Ho cambiato l'import di alcuni file all'interno dei blocchi CTABlock e ArgumentsInEvidence, da path relativo a path assoluto
=> fix: fixed few imports for CTABlock and ArgumentsInEvidence blocks

src/components/ItaliaTheme/View/BandoView/BandoUlterioriInformazioni.jsx, src/components/ItaliaTheme/View/Commons/Metadata.jsx, src/components/ItaliaTheme/View/Commons/Sponsors.jsx, src/components/ItaliaTheme/View/DocumentoView/DocumentoUlterioriInformazioni.jsx, src/components/ItaliaTheme/View/EventoView/EventoSponsors.jsx, src/components/ItaliaTheme/View/EventoView/EventoUlterioriInformazioni.jsx, src/components/ItaliaTheme/View/EventoView/EventoView.jsx, src/components/ItaliaTheme/View/NewsItemView/NewsItemMetadata.jsx, src/components/ItaliaTheme/View/PersonaView/PersonaUlterioriInformazioni.jsx, src/components/ItaliaTheme/View/ServizioView/ServizioUlterioriInformazioni.jsx, src/components/ItaliaTheme/View/UOView/UOMoreInfos.jsx, src/components/ItaliaTheme/View/VenueView/VenueMoreInfos.jsx, src/components/ItaliaTheme/View/index.js
Nei CT che possiedono questa sezione, ora il titolo della sezione viene mostrato solo se le informazioni che sono definite nel campo ulteriori_informazioni sono compilate.
Nei CT in cui questa sezione mostra anche altri campi/informazioni, il titolo della sezione viene mostrato solo se almeno uno di questi campi/informazioni è compilato/soddisfa i requisiti per essere mostrato
=> Fix ulteriori informazioni section

mrs.developer.json, package.json, src/customizations/volto-form-block/components/Field.jsx, src/customizations/volto-form-block/components/FormView.jsx, yarn.lock
Aggiunto sistema di monitoraggio bot con metodologia Honeypot per l'addon di Volto Form Block
=> Honeypot volto form block

src/config/italiaConfig.js, src/customizations/volto/components/theme/Login/Login.jsx, src/routes.js
These are the changes already merged in Volto (16) master: https://github.com/plone/volto/pull/3448
=> Customize password reset routes until we use Volto 16 (volto #3448)

theme/ItaliaTheme/Blocks/_sliderTemplate.scss
[US#34760](https://redturtle.tpondemand.com/entity/34760-blocco-slider-freccette-e-indicatore-numero)
Adattare le frecce e palline del slider alla grafica art-er.
Grafica art-er
https://projects.invisionapp.com/d/main#/loading
Result:
=> fix: slider arrows and dots styles fixed

src/components/ItaliaTheme/Footer/FooterSmall.jsx, src/components/ItaliaTheme/MenuSecondary/MenuSecondary.jsx, src/customizations/volto-secondarymenu/widget/SecondaryMenuConfigurationForm.jsx, src/customizations/volto-subfooter/widget/SubFooterConfigurationForm.jsx
Data-element added to subfooter menu and secondary menu
To subfooter:
data-element="faq"
data-element="report-inefficiency"
data-element="accessibility-link"
data-element="privacy-policy-link"
To secondary menu:
data-element="all-topics"
=> feat: data-element added to footer menu and secondary menu
