theme/extras/_forms.scss
theme/site.scss

Non si capisce dove cliccare
Vale per tutti i campi. 
Se si valuta una soluzione a blocchi per alcuni campi, comunque il layout deve essere fissato per gli altri
Idem nel caso in cui il campo si trovi nella sidebar di destra (anche lì c'è lo stesso pb)
Nel core di AGID mettere uno sfondo grigio su tutti i campi input

added background style for form fields

---

src/components/DesignTheme/View/Commons/SideMenu.jsx
src/components/DesignTheme/View/NewsItemView.jsx

Questa PR da una sistemata al menu laterale puntando correttamente le ancore e correggendo le label per fare uno statico più conforme alla realtà. Il primo link "descrizione" l'ho cambiato con "Notizia" e punta alla sezione a blocchi

update news side menu

---

src/config.js

Questo fix sistema il problema in maniera "dirty".
dirty perché [l'originale](https://github.com/plone/volto/blob/master/src/config/RichTextEditor/ToHTML.jsx#L121) gestisce anche il fatto che nel testo ci sia un a capo (shift+invio).
Quella gestione però si spacca se nel testo del blockquote ci sono delle parole con stili aggiuntivi (ad esempio BOLD).
Ho aperto una issue perché mi sfugge la logica con cui dovrebbe essere fatta questa cosa, e aspetto news da loro: https://github.com/plone/volto/issues/1601
Intanto possiamo usare questa customizzazione. L'unico side-effect è che non disegna l'a capo per ora, ma almeno non si spacca.

Fix problema del copia/incolla di testo

---

src/config.js

Rimosso il blocco leadimage da quelli aggiungibili nell'editor

[fix] removed leadimage block from available blocks

---

src/components/DesignTheme/Blocks/Listing/InEvidenceTemplate.jsx
src/components/DesignTheme/Blocks/Listing/NewsTemplate.jsx
theme/DesignTheme/Blocks/_newstemplate.scss

eg. for news return the 'tipologia_notizia' value
this is strictly related to https://github.com/RedTurtle/design.plone.contenttypes/pull/20
Nicola and Giulia I also assign this pr to you 'cause most of the templates on design-volto-theme are yours and you need to know this change.

change template to use the new design_italia_meta_type to detect content type

---

theme/_cms-ui.scss

Fix del problema del widget della tipologia (select) che quando la si apre va sotto al datepicker. c'è un esempio nel Ct Persona

fixed z-index for react_select menu

---

src/components/DesignTheme/View/NewsItemView.jsx
src/components/DesignTheme/View/ViewUtils.jsx

Modificato il metodo di calcolo del tempo di lettura di un documento. 
Ora viene calcolato solamente lato client prendendo il testo dall'elemento html del dom che lo contiene

Bug 10664 link nel testo tempo lettura

---

theme/ItaliaTheme/_main.scss
theme/_cms-ui.scss
theme/bootstrap-override/bootstrap-italia/_footer.scss
theme/site.scss

quando ora entri in edit, o vai su pagine dove viene mostrato l'h1 con classe documentFirstHeading, i font sono quelli di Italia, e non quelli di volto

fixed styles for fonts in cms-ui

---

src/components/ItaliaTheme/Blocks/SearchSections/Body.jsx
theme/ItaliaTheme/Blocks/_searchSections.scss
theme/site.scss
yarn.lock

Sistemati gli stili del blocco di ricerca delle sezioni, perchè era wrappato da un raw (a quanto pare inutile in quel caso) che provocava lo scorrimento orizzontale della pagina.
Cambiati anche il nome del file css e della classe del blocco in modo da uniformarli al nome del blocco (da searchServices a searchSections)

fixed searchSection block styles

---

src/components/ItaliaTheme/View/EventoView.jsx

Se l'organizzatore e' esterno, non mostriamo piu' le info relative a chi supporta l'evento, anche se il campo e' compilato

[dev] rimossa card evento supportato da se organizzatore esterno

---

src/customizations/components/manage/Blocks/Listing/ListingBody.jsx

Il pezzo modificato è relativo ai contenuti folderish e non segue i parametri della querystring.
Immagino fosse figlio di un copia incolla, su volto il calcolo è corretto e l'ho ripristinato

Fix Pagination data counts

---

src/components/ItaliaTheme/MegaMenu/MegaMenu.jsx
theme/bootstrap-override/bootstrap-italia/_megamenu.scss

Aggiunge:
- icone nei bottoni di toggle dei dropdown
- stile per "triangolino" di indicazione del dropdown aperto

added dropdown icon for megamenu

---

src/components/ItaliaTheme/View/EventoView/EventoView.jsx
src/components/ItaliaTheme/View/EventoView/Placeholder/AfterContent.jsx
src/components/ItaliaTheme/View/NewsItemView/NewsItemView.jsx
src/components/ItaliaTheme/View/NewsItemView/Placeholder/AfterContent.jsx
src/components/ItaliaTheme/View/PageView/PageView.jsx
src/components/ItaliaTheme/View/PageView/Placeholder/AfterContent.jsx
src/components/ItaliaTheme/View/PaginaArgomentoView/PaginaArgomentoView.jsx
src/components/ItaliaTheme/View/PaginaArgomentoView/PaginaArgomentoViewNoBlocks.jsx
src/components/ItaliaTheme/View/PaginaArgomentoView/Placeholder/AfterContent.jsx
src/components/ItaliaTheme/View/PersonaView/PersonaView.jsx
src/components/ItaliaTheme/View/PersonaView/Placeholder/AfterContent.jsx
src/components/ItaliaTheme/View/ServizioView/Placeholder/AfterContent.jsx
src/components/ItaliaTheme/View/ServizioView/ServizioView.jsx
src/components/ItaliaTheme/View/UOView/Placeholder/AfterContent.jsx
src/components/ItaliaTheme/View/UOView/UOView.jsx
src/components/ItaliaTheme/View/VenueView/Placeholder/AfterContent.jsx
src/components/ItaliaTheme/View/VenueView/VenueView.jsx
src/components/ItaliaTheme/View/__tests__/EventoView.test.jsx
src/components/ItaliaTheme/View/__tests__/PaginaArgomento.test.jsx
src/components/ItaliaTheme/View/__tests__/PersonaView.test.jsx
src/components/ItaliaTheme/View/index.js
src/components/ItaliaTheme/index.js

L'idea è quella di avere dei 'segnaposto' dove poter inserire contenuti custom per il comune per ogni view.
Per il momento è stato creato solamente il componente 'AfterContent' che mette un segnaposto dopo il contenuto. Ma in futuro potrebbe essere necessario avere altri segnaposto in altre posizioni della view, per questo motivo è stata creata una cartellina 'Placeholder' per ogni view.
Io e @nzambello abbiamo anche in mente di creare nei prossimi giorni, dei componenti separati per ogni pezzo della view, in modo da poter customizzare in maniera più semplice e meno invasiva le view dei contenttype.

added PlaceholderAfterContent for each view

---

src/components/ItaliaTheme/Footer/FooterInfos.jsx
src/components/ItaliaTheme/Footer/FooterMain.jsx
src/components/ItaliaTheme/Header/HeaderCenter.jsx
src/components/ItaliaTheme/Header/HeaderSlim.jsx
src/components/ItaliaTheme/View/Commons/ContentImage.jsx
src/config.js

Ora abbiamo un oggetto di configurazione per dover customizzare il meno possibile nei progetti figli
```js
export const siteConfig = {
italiaThemeViewsConfig: {
imagePosition: 'afterHeader', // possible values: afterHeader, documentBody
},
properties: {
siteTitle: 'Nome del Comune',
siteSubtitle: "Uno dei tanti Comuni d'Italia",
parentSiteTitle: 'Nome della Regione',
parentSiteURL: 'https://www.governo.it',
footerInfos:
'Via Roma 0 - 00000 Lorem Ipsum Codice fiscale / P. IVA: 000000000',
},
socialSettings: [
{
title: 'Facebook',
url: 'https://facebook.com',
icon: 'it-facebook',
},
{
title: 'GitHub',
url: 'https://github.com',
icon: 'it-github',
},
{
title: 'Twitter',
url: 'https://twitter.com',
icon: 'it-twitter',
},
],
};
```

dev: added siteConfig for site specific properties

---

src/components/ItaliaTheme/Blocks/Listing/CardWithImageTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/InEvidenceTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/RibbonCardTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateDefault.jsx
src/components/ItaliaTheme/View/Commons/Dates.jsx
src/components/ItaliaTheme/View/Commons/GenericCard.jsx
src/components/ItaliaTheme/View/Commons/RelatedItems.jsx
src/components/ItaliaTheme/index.js
src/customizations/components/theme/View/EventDatesInfo.jsx
src/helpers/ListingHelper.js
src/helpers/index.js
theme/ItaliaTheme/Blocks/_cardWithImageAndInEvidence.scss
theme/ItaliaTheme/Blocks/_listing.scss
theme/ItaliaTheme/Blocks/_ribbonCardTemplate.scss

mostrate le date dell'evento e della notizia nei vari template del listing.
Nel caso in cui si tratti di un evento con ricorrenza, d'accordo con Serena è stato aggiunto in fondo alla card il link al dettaglio dell'evento la cui label è 'Questo evento ha più date: vedi tutte'. In questo modo evitiamo di mostrare nella card una sbrodolata potenzialmente infinita di date della ricorrenza. 
Per esempio:

Us 10947 fix listing dates

---

src/components/ItaliaTheme/View/Commons/ContactLink.jsx

Aggiunta una funziona con RegEx per mettere i link solo su effettivi numeri di telefono/fax e email. Infatti nei campi tel, fax, email può esserci scritto del testo. 
Ad esempio, se nel testo inserisco 
_Ufficio: 0532/111222333 - Casa: 0532-222222 - Cell: 333 333333333_ 
verranno automaticamente messi i link solamente sui numeri di telefono.
Lo stesso meccanismo vale per il campo email, il check viene fatto sulle mail
Voi che ne sapete forse piu di me sulle RegEx, dateci un occhio!

added regex for contactlinks

---

src/components/ItaliaTheme/Blocks/Calendar/Body.jsx
src/components/ItaliaTheme/Blocks/Calendar/Edit.jsx

Aggiunto come filtro di default gli eventi in modo da non mostrare un calendario vuoto appena lo si crea.

aggiunto filtro default che recuper gli eventi

---

src/components/ItaliaTheme/Blocks/Calendar/Body.jsx
src/components/ItaliaTheme/Blocks/Listing/Options/BgColor/BgColor.jsx
src/components/ItaliaTheme/Blocks/Listing/Options/BgColor/colors.js
src/components/ItaliaTheme/Blocks/Listing/Options/DefaultOptions.jsx
src/components/ItaliaTheme/Blocks/Listing/Options/SimpleCardTemplateOptions.jsx
src/components/ItaliaTheme/index.js
src/components/ItaliaTheme/manage/Widgets/ColorListWidget.jsx
src/customizations/components/manage/Blocks/Listing/ListingBody.jsx
theme/_cms-ui.scss

Ora si possono definire dei colori di sfondo aggiuntivi per i blocchi listing, oltre al grigio di base.
Per farlo, basta che ne vostro sito fate l'override di questo file src/components/ItaliaTheme/Blocks/Listing/Options/BgColor/colors.js
e definite il vostro elenco di colori.
Dovrete poi aggiungere gli stili nei vostri scss

added customizable listing bg_color

---

src/components/ItaliaTheme/Blocks/Listing/Options/SimpleCardTemplateOptions.jsx
src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateDefault.jsx
src/config.js
src/customizations/components/manage/Blocks/Listing/ListingBody.jsx
theme/ItaliaTheme/Blocks/_simpleCardTemplate.scss
theme/_cms-ui.scss

In pratica, nel template 'Card semplice' del listing, è possibile spuntare una opzione per aggiungere dei bottoni che consentono all'utente di filtrare ulteriormente i risultati per path. Per ogni bottone si può indicare la label e il percorso su cui filtrare gli elementi.

Template filtri sezione us 14684

---

src/components/ItaliaTheme/View/Commons/Metadata.jsx

Se nelle categorie non abbiamo valori significativi e non le usiamo per mandare alla ricerca, allora forse vale la pena non mostrarle.
Rimane possibile mostrarle per alcune viste aggiungendo la prop

feat: remove tags as default

---

package.json

quando si fa un commit, prima del commit viene lanciato yarn i18n e i file delle traduzioni vengono automaticamente aggiunti al commit. 
In questo modo siamo sempre sicuri di avere le traduzioni generate, anche in fase di creazione di un nuovo sito

Yarn i18n on commit

---

theme/ItaliaTheme/Blocks/_gridGalleryTemplate.scss

il testo bianco sulle fotografie non è sempre leggibile. Essendo un modello generale, dovrebbe essere pensato per evitare il rischio di situazioni non accessbili. Serve quindi al testo, qualcosa tipo uno sfondo semiopaco scuro per garantire sempre la leggibilità es. RGB(0,0,0,0.6).
Come ora previsto per l’hover, metterei uno sfondo sempre da scurire all'hover/focus

fix(a11y): grid gallery listing darker

---

src/components/ItaliaTheme/Footer/FooterMain.jsx
src/components/ItaliaTheme/Footer/FooterSmall.jsx
src/components/ItaliaTheme/Header/HeaderCenter.jsx
src/components/ItaliaTheme/Header/HeaderSlim.jsx
src/config/italiaConfig.js
src/customizations/volto/components/theme/AppExtras/AppExtras.jsx
src/customizations/volto/components/theme/Navigation/Navigation.jsx
src/helpers/config.js
src/helpers/index.js

Permette di poter tradurre le properties del sito per i siti multilingua. 
Come funziona:
- se la property è una stringa viene usata la stringa
- se la property è un oggetto:
-- se nell'oggetto c'è una property con la lingua corrente, viene preso il valore di quella property, oppure il valore della property 'default' (es. di oggetto: {'default':'Nome del sito', 'it':'Nome del sito', 'en': 'Site name'}
-- se nell'oggetto non c'è nè la property corrispondente alla lingua corrente, nè la property 'default' viene ritornato l'oggetto stesso.
In questo modo non dobbiamo cambiare la configurazione dei siti che abbiamo già, e dobbiamo eventualmente farlo solo per i siti multilingua

chore: enable translation for siteProperties

---

src/customizations/volto/components/manage/Blocks/Listing/ListingBody.jsx

C'era un problema che hanno segnalato in call:
se sono in edit e inserisco nei criteri di ricerca di un listing una ricerca per path, o comunque un criterio di ricerca dove la condizione viene inserita in un campo di testo (per cui l'utente può essere piu veloce a scrivere di quanto impiega il server a rispondere), non sempre l'anteprima dei risultati del listing è corretta.

fix: fixed unload results in editMode if query params changes

---

.github/workflows/develop.yml
.github/workflows/master.yml

Add a workflow to run on pull request approval.
This workflow merge the active PR branch into `develop` and deploys it to rancher.
The "master" workflow is now running on releases only

ci: add develop workflow

---

package.json
src/components/ItaliaTheme/Icons/Icon.jsx
src/components/ItaliaTheme/manage/Widgets/IconPreviewWidget.jsx
src/config/italiaConfig.js
yarn.lock

Now you can use far and fab icon set (default is fas).
If you don't write prefix, default prefix is 'fas'.
If you want icons from 'Regular' or from 'Brands' set, you could add prefix before icon name, for example: 'far angry' or 'fab accessible-icon'. 
Writing 'angry' or 'fas angry' is the same.

chore: added brand icons and enabled usage of regular icons

---

src/components/ItaliaTheme/View/PageView/PageView.jsx

By default they are not displayed.
If you want to display share buttons, you have to check the relative option in object fields.

Dispalyed share buttons in content-type Document

---

theme/ItaliaTheme/Subsites/_mixin.scss
theme/ItaliaTheme/Subsites/_templates.scss
theme/ItaliaTheme/Subsites/bootstrap-italia/custom/_chips.scss
theme/ItaliaTheme/Subsites/bootstrap-italia/custom/_header.scss
theme/ItaliaTheme/Subsites/bootstrap-italia/custom/_headercenter.scss
theme/ItaliaTheme/Subsites/bootstrap-italia/custom/_navigation.scss
theme/ItaliaTheme/Subsites/templates/_light-pink.scss
theme/ItaliaTheme/Subsites/templates/_light-teal.scss
theme/ItaliaTheme/Subsites/templates/_light-yellow.scss
theme/ItaliaTheme/Subsites/templates/_white.scss
theme/site.scss

Aggiunti nuovi colori per i sottositi come previsto dallo studio grafico, che saranno:
- white
- yellow
- magenta
- teal
- light-yellow
- light-pink
- light-teal
- light-blue

feat: added new subsites colors

---

theme/bootstrap-override/bootstrap-italia/_megamenu.scss

Pareva non raggiungibile, in realtà solo non visibile

fix: megamenu close button outline

---

src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateCompact.jsx
src/components/ItaliaTheme/View/Commons/Argument/ArgumentIcon.jsx
theme/ItaliaTheme/Blocks/_simpleCardTemplate.scss
theme/ItaliaTheme/Subsites/ItaliaTheme/Views/_common.scss
theme/ItaliaTheme/Views/_common.scss
theme/_site-variables.scss

Sistemata la gestione degli stili delle icone degli argomenti e la visualizzazione dell'icona nel template 'Card semplice - Compatto' del blocco elenco, secondo le grafiche agid.
Ora esistono due variabili: $argument-icon-color e $argument-icon-bg che si possono usare nei siti per cambiarne i colori.

chore: fixed argument icon styles

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/Listing/SliderTemplate.jsx
src/config/Blocks/ListingOptions/sliderTemplate.js
theme/ItaliaTheme/Blocks/_sliderTemplate.scss

Ora nel template Slider del blocco elenco, ci sono queste nuove funzionalità con i seguenti valori di default:
I valori impostati di default non alterano gli slider esistenti

chore: added listing SliderTemplate features

---

theme/ItaliaTheme/Blocks/_searchSections.scss

Il bottone di searchSections nel block chooser aveva gli stili dell'intero blocco applicati, quindi era altissimo.

Fix allo stile del bottone del blocco searchSections

---

src/components/ItaliaTheme/View/Commons/WideImage.jsx

Fissato un bug nelle immagini in testata, per cui se si andava da un contenuto ad un altro cliccando su un link presente in pagina, l'immagine in testata non veniva aggiornata e continuava a vedersi l'immagine in testata del contenuto precedente.

fix: fixed WideImage on route change

---

src/components/ItaliaTheme/Search/utils.js

C'era un problema negli argomenti della ricerca, sia nella popup di ricerca, sia nella sidebar laterale della pagina dei risultati, non venivano mostrati correttamente perchè dal BE non arrivava più il campo 'path' (probabilmente da quando è stata tolta la fullobjects?).

fix: fixed topics in search

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/Listing/CardWithImageTemplate.jsx

trovato guardando roba per Reggio con i listing cardWithImage a 4 colonne, era
ora si vede cosi' dopo le modifiche

fix: 4th element now shows image in CardWithImageTemplate with 4 columns

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/View/Commons/ContactLink.jsx

Ci sono dei problemi con email del tipo 'certificazioni-bollatura@re.camcom.it' che hanno trattini all'interno, apro la pr per capire se la modifica apportata è corretta o se la regex era stata fatta così per un motivo specifico che non so

fix: email address with dash

---

src/components/ItaliaTheme/Breadcrumbs/Breadcrumbs.jsx
src/components/ItaliaTheme/Breadcrumbs/GoogleBreadcrumbs.jsx

A seguito di una segnalazione di GoogleSearch console su un sito con DesignVoltoTheme, sono stati aggiunti i dati strutturati delle breadcrumbs per goolge: https://developers.google.com/search/docs/advanced/structured-data/breadcrumb

feat: added google breadcrumbs Structured data

---

src/components/ItaliaTheme/Blocks/Listing/SmallBlockLinksTemplate.jsx
theme/ItaliaTheme/Blocks/_smallblockLinkstemplate.scss

Questo sistema il problema con le immagini visto su Safari. Purtroppo Safari tratta i flexbox in maniera diversa dal resto del mondo.

Fix small block link image

---

theme/ItaliaTheme/Blocks/_cardWithSlideUpTextTemplate.scss

Risolto un problema di sovrapposizione del blocco con il dropdown del datepicker

fix: z-index of card with slide up text template

---

src/components/ItaliaTheme/View/TrasparenzaView/TrasparenzaView.jsx

Senza questo fix la vista dà errore se applicata a una pagina normale

Fix trasparenza_view query condition

---

src/config/italiaConfig.js

Rimuoverei questa riga. Ad oggi non è possibile settare al volo questo parametro con una variabile d'ambiente, perché questa vince di base, quindi l'unico modo sarebbe fare l'override in ogni proprio progetto personale, ove necessario.

chore: remove fixed dev proxy to api path

---

src/config/Blocks/listingVariations.js
src/customizations/volto/components/manage/Blocks/Listing/withQuerystringResults.jsx

Actually we are not able to read "fullobjects" option from variation configuration

fix: reading fullobjects from variation config

---

src/components/ItaliaTheme/Blocks/ContactsBlock/Block/ViewBlock.jsx
src/components/ItaliaTheme/Blocks/CountDown/View.jsx
src/helpers/index.js
src/helpers/redraftHelper.js
theme/ItaliaTheme/Blocks/_contacts.scss

- Aggiunta una funzione tra gli helpers per quegli elementi textEditor che una volta compilati e cancellato il contenuto il blocco continua ad essere mostrato vuoto
- Applicate modifiche al testo del blocco contatti che fuoriusciva dalle card se troppo lungo

chore: added readraft helper function and fixed text of contacts form

---

package.json
src/components/ItaliaTheme/Blocks/Listing/GridGalleryTemplate.jsx
yarn.lock

Qui non si vede più di tanto, la vera modifica è su volto, che ora tiene conto anche del device pixel ratio: https://github.com/plone/volto/blob/7b6af2e44585f9cfe7127dc61e7430777ba89f48/src/components/theme/Image/Image.jsx#L61 
motivo per cui su mobile si vedevano molto sgranate.
Le immagini full-width purtroppo su monitor grandi avranno sempre un po' di sgranatura, perchè la miniatura massima è di 1600px

chore: improve srcset image quality

---

package.json
yarn.lock

Aggiornata la versione di Volto per fissare un bug che si verificava nel momento in cui si incollava un url interno in un campo link o in un blocco immagine

fix: fix paste links and image urls

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/volto.pot
package.json
src/components/ItaliaTheme/Blocks/VideoGallery/Block/ViewBlock.jsx
src/components/ItaliaTheme/View/Commons/EmbeddedVideo.jsx
src/customizations/volto/components/manage/Blocks/Video/Body.jsx
src/customizations/volto/components/manage/Blocks/Video/Edit.jsx
src/customizations/volto/components/manage/Blocks/Video/View.jsx
theme/ItaliaTheme/Blocks/_video.scss
theme/ItaliaTheme/Blocks/_videoGallery.scss
theme/ItaliaTheme/Views/_embeddedVideo.scss
theme/site.scss
yarn.lock

Ora i video vengono caricati in maniera 'Leggera'.
Ovvero, invece di mettere subito in pagina l'iframe, viene prima messa in pagina l'immagine di anteprima del video.
Al click sull'immagine di anteprima, viene iniettato in pagina l'html dell'iframe. 
Dopodichè (so che è un po' brutto ma non sono riuscita a fare altrimenti) bisogna cliccare nuovamente sull'iframe per far partire il video. 
Anche la navigazione con la tastiera non è fantastica. 
Ne ho parlato con Serena, e non c'è altra soluzione.. tra l'altro abbiamo visto che usa questa tecnica anche google sul sito di support..
Voi avete idee?

feat: light loading of videos

---

theme/ItaliaTheme/Addons/volto-gdpr-privacy.scss

- fissato un bug che rendeva cliccabile l'area sottostante ai bottoni disabilitati nella colonna di sinistra del Cookie banner
- aggiunto uno z-index più elevato perchè elementi come mappa di leaflet e bottone "Torna su" si sovrapponevano al banner

fix: fixed click under disabled button and z-index cookie banner

---

theme/ItaliaTheme/Blocks/_form.scss

Le label dinamiche dei form ora rimangono fisse sopra ai campi di input ed è stata rimossa l'interruzione di linea coi tre puntini di sospensione per permettere al testo di andare a capo
Label nowrap
Label con la modifica

Wrap animation label form block

---

src/components/ItaliaTheme/Blocks/TextCard/CardWithImage/Block.jsx
src/components/ItaliaTheme/Blocks/TextCard/SimpleCard/Block.jsx

Rimosso il focus nel testo dai blocchi card semplice e con immagine che creava un bug alla creazione di un link nel testo di draft js

fix: removed focus from simple and image card blocks to fix draftjs link

---

theme/ItaliaTheme/Blocks/_sliderTemplate.scss

Sistemato regole per riempire orizzontalmente e verticalmente lo slider senza stracciare e tagliare troppo le immagini

fix: fixed width and height of slider images

---

theme/ItaliaTheme/Blocks/_photogallerytemplate.scss

Risolto un bug che non mandava a capo la descrizione del template elenco photogallery

fix: fixed description alignment of photogallery listing template

---

src/components/ItaliaTheme/Blocks/Listing/Commons/CardCalendar.jsx

Abbiamo trovato eventi che davano errore purché senza date, questa fix ci aiuta a priori ad evitare che si rompano i template elenco Card con Immagine e In evidenza

fix: fixed dates of cardCalendar component

---

src/customizations/volto/components/manage/Contents/Contents.jsx
src/routes.js

Aggiunta customizzazione per volto15 già risolta su volto16 in attesa di un upgrade (riferimento qui https://github.com/plone/volto/pull/3528), per risolvere un problema sul pulsante "more" della toolbar sx di volto, sotto alla cartella 'homepage' ed entrando in uno dei contenuti sottostanti, rimaneva solo l'azione di condivisione
Prima
Dopo

fix: fixed more action from the toolbar

---

src/components/ItaliaTheme/GalleryPreview/GalleryPreview.jsx
theme/ItaliaTheme/Components/_galleryPreview.scss

Dentro il content type "Notizie e comunicati stampa", quando ci sono immagini dentro la cartella "Multimedia", queste sono mostrate in griglia su contenuto della notizia. Cliccando su un'immagine viene visualizzata un'anteprima. In questa modale è stato aggiunta la descrizione e identificato il titolo con una tag <H*>

chore: description added to gallery image popup

---

theme/ItaliaTheme/Blocks/_cardWithImageAndInEvidence.scss

US34702
Ticket 34323
Dentro del blocco elenco tipo card con immagine, se sono filtrati "persone" e le persone hanno la stessa foto di profilo, o sia, la stessa persona 2 o più volte, però con contenuti diversi, le immagine diventavano diversi tra di loro se le opzioni del blocco sulla sidebar cambiano.
Con la sistemazione le immagine rimangono sempre con 1/3 della card senza variazione di altezza.

fix: person image inside card with image fixed

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/Listing/CardWithImageTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/CardWithSlideUpTextTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/CompleteBlockLinksTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/ContentInEvidenceTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/InEvidenceTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/RibbonCardTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateCompact.jsx
src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateDefault.jsx
src/components/ItaliaTheme/Blocks/Listing/SquaresImageTemplate.jsx
src/config/Blocks/ListingOptions/cardWithImageTemplate.js
src/config/Blocks/ListingOptions/cardWithSlideUpTextTemplate.js
src/config/Blocks/ListingOptions/completeBlockLinksTemplate.js
src/config/Blocks/ListingOptions/inEvidenceTemplate.js
src/config/Blocks/ListingOptions/ribbonCardTemplate.js
src/config/Blocks/ListingOptions/simpleCardTemplate.js
src/config/Blocks/ListingOptions/utils.js
src/config/Blocks/listingVariations.js

[Us#34658](https://redturtle.tpondemand.com/entity/34658-nei-blocchi-elenco-inserire-la-possibilita)
Nella sidebar dei blocchi elenco, è stato aggiunto un campo in cui si può scrivere scegliere un ID. Tale ID deve essere applicato dal personale RT come valore del data-element sul link delle card su blocchi elenco:
- Card semplice
- Card con immagine
- in evidenza
- Contenuto in evidenza
- Card con nastro
- Card con testo animato
- Quadratoni con immagine
- Blocco link completo
Il campo aggiunto è un select con:
- service-category-link
- topic-element
- service-link
- administration-element

chore: data element insertion - lighthouse id - block listing
